# API Keys - Keep this secret!
TMDB_API_KEY = "e1b94508c11b0150d17dc8c721f34ccf"
STREAM_API_KEY = "b572f9e3bdmshb3c2fcbd0c5b85dp1f2278jsn07c62d961686"
GROQ_API_KEY = "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"